"""Unified proactive monitoring system for MERLIN.

Subscribes to telemetry updates and evaluates each state snapshot against
callout rules, deviation checks, and emergency detection.  Events are
queued in priority order (emergencies first) for the web server to
deliver to the browser.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import Any

from .emergency import EmergencyDetector, EmergencyResponse
from .sim_client import FlightPhase, SimState

# Optional modules that may not exist yet -- provide graceful fallbacks.
try:
    from .callouts import CalloutEvaluator  # type: ignore[import-not-found]
except ImportError:
    CalloutEvaluator = None  # type: ignore[assignment,misc]

try:
    from .deviation_monitor import DeviationMonitor  # type: ignore[import-not-found]
except ImportError:
    DeviationMonitor = None  # type: ignore[assignment,misc]

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Event data class
# ---------------------------------------------------------------------------


@dataclass(order=True)
class ProactiveEvent:
    """A proactive event generated by the monitoring system.

    ``priority`` drives delivery order: 3 = emergency, 2 = warning,
    1 = caution, 0 = informational.  The ``order`` comparison uses
    *descending* priority so that higher-priority events sort first
    when using a min-heap (``asyncio.PriorityQueue``).
    """

    # Fields used for priority ordering (sort key comes first)
    _sort_key: int = field(init=False, repr=False)

    type: str = field(compare=False)  # "callout", "deviation", "emergency", "checklist_offer"
    priority: int = field(compare=False)  # 0=info, 1=caution, 2=warning, 3=emergency
    message: str = field(compare=False)  # What MERLIN should say
    tts_override: bool = field(default=False, compare=False)
    data: dict[str, Any] = field(default_factory=dict, compare=False)

    def __post_init__(self) -> None:
        # Negate priority so higher priorities sort first in a min-heap.
        self._sort_key = -self.priority


# ---------------------------------------------------------------------------
# Deviation thresholds
# ---------------------------------------------------------------------------


@dataclass
class DeviationThresholds:
    """Configurable limits for built-in deviation detection."""

    overspeed_ias: float = 250.0  # knots -- typical Vne for piston singles
    max_bank_angle: float = 60.0  # degrees
    altitude_bust_ft: float = 300.0  # feet deviation from assigned altitude


# ---------------------------------------------------------------------------
# Callout thresholds
# ---------------------------------------------------------------------------


@dataclass
class CalloutThresholds:
    """Thresholds for altitude-crossing and speed callouts."""

    v1_speed: float = 60.0  # knots
    rotate_speed: float = 65.0  # knots
    altitude_callout_levels: tuple[float, ...] = (1000.0, 500.0, 200.0, 100.0)


# ---------------------------------------------------------------------------
# Phase transition checklist mappings
# ---------------------------------------------------------------------------

_PHASE_CHECKLIST_OFFERS: dict[tuple[FlightPhase, FlightPhase], str] = {
    (FlightPhase.PREFLIGHT, FlightPhase.TAXI): (
        "Before-taxi checklist available. Want me to run it?"
    ),
    (FlightPhase.TAXI, FlightPhase.TAKEOFF): ("Takeoff checklist -- ready when you are."),
    (FlightPhase.CLIMB, FlightPhase.CRUISE): "Cruise checklist available. Say the word.",
    (FlightPhase.CRUISE, FlightPhase.DESCENT): (
        "Descent checklist ready. Want me to walk you through it?"
    ),
    (FlightPhase.DESCENT, FlightPhase.APPROACH): "Approach checklist standing by.",
    (FlightPhase.APPROACH, FlightPhase.LANDING): "Before-landing checklist -- ready?",
}


# ---------------------------------------------------------------------------
# ProactiveMonitor
# ---------------------------------------------------------------------------


class ProactiveMonitor:
    """Unified telemetry monitor that generates proactive events.

    Subscribes to the TelemetryClient and evaluates each state update
    against callout rules, deviation checks, and emergency detection.
    Events are queued for the web server to pick up and send to the browser.
    """

    def __init__(
        self,
        emergency_detector: EmergencyDetector | None = None,
        deviation_thresholds: DeviationThresholds | None = None,
        callout_thresholds: CalloutThresholds | None = None,
    ) -> None:
        self._event_queue: asyncio.PriorityQueue[ProactiveEvent] = asyncio.PriorityQueue()
        self._emergency_detector = emergency_detector or EmergencyDetector()
        self._deviation_thresholds = deviation_thresholds or DeviationThresholds()
        self._callout_thresholds = callout_thresholds or CalloutThresholds()

        self._prev_state: SimState | None = None
        self._prev_phase: FlightPhase = FlightPhase.PREFLIGHT

        # Track callouts already fired to avoid repeats within the same phase.
        self._fired_callouts: set[str] = set()

        # Optional external evaluators (from callouts.py / deviation_monitor.py).
        self._callout_evaluator = CalloutEvaluator() if CalloutEvaluator is not None else None
        self._deviation_monitor = DeviationMonitor() if DeviationMonitor is not None else None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def on_telemetry_update(self, state: SimState) -> None:
        """Called on each telemetry update.  Evaluates all proactive systems."""
        prev = self._prev_state

        # 1. Emergency conditions (priority 3)
        if prev is not None:
            self._check_emergencies(prev, state)

        # 2. Deviation alerts (priority 2)
        self._check_deviations(state)

        # 3. Callouts (priority 0-1)
        if prev is not None:
            self._check_callouts(prev, state)

        # 4. Phase transitions -> checklist offers (priority 0)
        current_phase = state.flight_phase
        if current_phase != self._prev_phase:
            self._check_phase_transition(self._prev_phase, current_phase)
            # Reset fired callouts when phase changes.
            self._fired_callouts.clear()
            self._prev_phase = current_phase

        self._prev_state = state

    async def get_next_event(self, timeout: float = 0.1) -> ProactiveEvent | None:
        """Get the next proactive event, or None if queue is empty."""
        try:
            return await asyncio.wait_for(self._event_queue.get(), timeout=timeout)
        except TimeoutError:
            return None

    def get_pending_count(self) -> int:
        """Return number of pending events."""
        return self._event_queue.qsize()

    # ------------------------------------------------------------------
    # Emergency checks
    # ------------------------------------------------------------------

    def _check_emergencies(self, prev: SimState, curr: SimState) -> None:
        """Delegate to EmergencyDetector and enqueue any result."""
        response: EmergencyResponse | None = self._emergency_detector.evaluate(prev, curr)
        if response is not None:
            event = ProactiveEvent(
                type="emergency",
                priority=3,
                message=response.spoken_response,
                tts_override=True,
                data={
                    "emergency_type": response.emergency_type.value,
                    "emergency_response": {
                        "title": response.title,
                        "immediate_actions": response.immediate_actions,
                        "followup_checklist": response.followup_checklist,
                        "squawk": response.squawk,
                    },
                },
            )
            self._event_queue.put_nowait(event)
            logger.critical("Emergency event queued: %s", response.emergency_type.value)

    # ------------------------------------------------------------------
    # Deviation checks
    # ------------------------------------------------------------------

    def _check_deviations(self, state: SimState) -> None:
        """Check for parameter deviations (overspeed, bank angle, altitude bust)."""
        # Delegate to external deviation monitor if available.
        if self._deviation_monitor is not None:
            try:
                external_events = self._deviation_monitor.evaluate(state)  # type: ignore[union-attr]
                for evt in external_events:
                    self._event_queue.put_nowait(evt)
            except Exception:
                logger.exception("External deviation monitor error")

        t = self._deviation_thresholds

        # Overspeed
        if state.speeds.indicated_airspeed > t.overspeed_ias and not state.on_ground:
            self._enqueue_deviation(
                f"Overspeed — {state.speeds.indicated_airspeed:.0f} knots. Reduce power.",
                {
                    "parameter": "ias",
                    "value": state.speeds.indicated_airspeed,
                    "limit": t.overspeed_ias,
                },
            )

        # Excessive bank angle
        bank = abs(state.attitude.bank)
        if bank > t.max_bank_angle and not state.on_ground:
            self._enqueue_deviation(
                f"Bank angle {bank:.0f} degrees. Level the wings.",
                {"parameter": "bank", "value": bank, "limit": t.max_bank_angle},
            )

        # Altitude bust (only meaningful during cruise with AP engaged)
        if (
            state.flight_phase == FlightPhase.CRUISE
            and state.autopilot.master
            and abs(state.position.altitude_msl - state.autopilot.altitude) > t.altitude_bust_ft
        ):
            self._enqueue_deviation(
                (
                    f"Altitude deviation — {state.position.altitude_msl:.0f} feet, "
                    f"assigned {state.autopilot.altitude:.0f}."
                ),
                {
                    "parameter": "altitude",
                    "value": state.position.altitude_msl,
                    "assigned": state.autopilot.altitude,
                },
            )

    def _enqueue_deviation(self, message: str, data: dict[str, Any]) -> None:
        event = ProactiveEvent(
            type="deviation",
            priority=2,
            message=message,
            tts_override=False,
            data=data,
        )
        self._event_queue.put_nowait(event)

    # ------------------------------------------------------------------
    # Callout checks
    # ------------------------------------------------------------------

    def _check_callouts(self, prev: SimState, curr: SimState) -> None:
        """Generate callouts for V1, rotate, and altitude crossings."""
        # Delegate to external callout evaluator if available.
        if self._callout_evaluator is not None:
            try:
                external_events = self._callout_evaluator.evaluate(prev, curr)  # type: ignore[union-attr]
                for evt in external_events:
                    self._event_queue.put_nowait(evt)
            except Exception:
                logger.exception("External callout evaluator error")

        ct = self._callout_thresholds

        # V1 callout
        if (
            curr.flight_phase == FlightPhase.TAKEOFF
            and "v1" not in self._fired_callouts
            and prev.speeds.indicated_airspeed < ct.v1_speed <= curr.speeds.indicated_airspeed
        ):
            self._fired_callouts.add("v1")
            self._enqueue_callout("V1.", priority=1, data={"callout": "v1"})

        # Rotate callout
        if (
            curr.flight_phase == FlightPhase.TAKEOFF
            and "rotate" not in self._fired_callouts
            and prev.speeds.indicated_airspeed < ct.rotate_speed <= curr.speeds.indicated_airspeed
        ):
            self._fired_callouts.add("rotate")
            self._enqueue_callout("Rotate.", priority=1, data={"callout": "rotate"})

        # Altitude crossing callouts (descending through AGL levels)
        if curr.flight_phase in (FlightPhase.APPROACH, FlightPhase.LANDING):
            for level in ct.altitude_callout_levels:
                key = f"alt_{int(level)}"
                if (
                    key not in self._fired_callouts
                    and prev.position.altitude_agl > level >= curr.position.altitude_agl
                ):
                    self._fired_callouts.add(key)
                    self._enqueue_callout(
                        f"{int(level)} feet.",
                        priority=0,
                        data={"callout": "altitude", "altitude_agl": level},
                    )

    def _enqueue_callout(
        self,
        message: str,
        *,
        priority: int = 0,
        data: dict[str, Any] | None = None,
    ) -> None:
        event = ProactiveEvent(
            type="callout",
            priority=priority,
            message=message,
            data=data or {},
        )
        self._event_queue.put_nowait(event)

    # ------------------------------------------------------------------
    # Phase-transition checklist offers
    # ------------------------------------------------------------------

    def _check_phase_transition(
        self,
        prev_phase: FlightPhase,
        new_phase: FlightPhase,
    ) -> None:
        offer = _PHASE_CHECKLIST_OFFERS.get((prev_phase, new_phase))
        if offer:
            event = ProactiveEvent(
                type="checklist_offer",
                priority=0,
                message=offer,
                data={"from_phase": prev_phase.value, "to_phase": new_phase.value},
            )
            self._event_queue.put_nowait(event)
            logger.info(
                "Checklist offer queued: %s -> %s",
                prev_phase.value,
                new_phase.value,
            )
